name: unbdine
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.5+1
  fluttertoast: ^8.1.1
  lottie: ^1.4.3
  google_fonts: ^3.0.1
  flutter_phoenix: ^1.1.0
  hooks_riverpod: ^2.1.1
  package_info_plus: ^1.4.3+1
  flutter_keyboard_visibility: ^5.4.0
  firebase_auth: any
  firebase_core: any
  firebase_auth_oauth: any
  cloud_firestore: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/animations/
    - assets/images/